# Generated by Django 4.2.1 on 2023-10-07 16:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=builtins.input),
            preserve_default=False,
        ),
    ]
