# Generated by Django 4.2.1 on 2023-10-07 16:41

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.TextField(default=builtins.input),
            preserve_default=False,
        ),
    ]
