# Generated by Django 4.2.1 on 2023-10-07 16:48

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.CharField(default=builtins.input, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(max_length=122),
        ),
    ]
